name: Imprime data atual

on:
  push:
  
jobs:
  imprime_data_ubuntu:
    name: Imprime data atual - Ubuntu
    runs-on: ubuntu-latest
    
    steps:
      - name: Imprime data atual
        run: date
  
  imprime_data_windows:
    name: Imprime data atual - Windows
    runs-on: windows-latest
        
    steps:
      - name: Imprime data atual
        run: date
        
  imprime_macos:
    name: Imprime data atual - Macos
    runs-on: macos-lastet
    
    steps:
      - name: Imprime data atual
        run: date
    
  imprime_data_ubuntu2:
    name: Imprime data atual - Ubuntu2
    runs-on: ubuntu-lastet
    needs: [imprime_data_ubuntu, imprime_data_windows, imprime_macos] 
    
    steps:
      - name: Imprime data atual
        run: date
    
