name: Workflow exercicio 2

on:
  push:
  
jobs:

  checkout_code:
    name: Faz checkout do nome
    runs-on: ubuntu-latest
              
    steps:
      - name: Checkout repositório
        uses: action/checkout@v3.3.0
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{vars.NOME}}
          path: .
      
